spring.application.name=auth
jwt.secret=${JWT_SECRET}

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${MONGODB_DATABASE:auth_db}
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE:auth_db}
spring.data.mongodb.auto-index-creation=true
